### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Eraser

### ISSUE THREAD

**Issue by amye** [cncf/toc#1092]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/legal/trademark-usage>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk - project-onboarding@cncf.io is the best email to send those to
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: https://github.com/enterprises/cncf
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to projects@cncf.io
- [x] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [ ] Book time with the team with <http://project-meetings.cncf.io>
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by bridgetkromhout** [comment]
Thanks, @amye! We will begin work on the project-level tasks soon (summer vacations being what they are).

**Comment by lukaszgryglicki** [comment]
DevStats [instance](https://eraser.devstats.cncf.io) added. Also added in [All CNCF projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1) instance. Will be fully-added to all other [All CNCF](https://all.devstats.cncf.io) dashboards on Friday (affiliations research started today, and will be imported as it progresses).

**Comment by salaxander** [comment]
@amye - I'm back from vacation starting now so we'll get started on these items this week and into next week :) 

CC @sozercan @pmengelbert @ashnamehrotra

**Comment by salaxander** [comment]
Pasting the list in a new comment so it will allow me to check off progress :) 

From the project side, please ensure that you:

- [ ] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
- [ ] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [ ] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [ ] Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [ ] Understand the trademark guidelines: https://www.linuxfoundation.org/legal/trademark-usage
- [ ] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
- [ ] Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
- [ ] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
- [ ] Is your project in its own separate neutral github organization?
- [ ] Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io/
- [ ] Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
- [ ] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
- [ ] Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

Things that CNCF will need from the project:

- [ ] Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk - [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io) is the best email to send those to
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
- [ ] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: https://github.com/enterprises/cncf
- [ ] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [ ] GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [ ] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [ ] Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
- [ ] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en

**Comment by salaxander** [comment]
@amye - Now that the logo is added to /artwork, our onboarding is officially complete :)

**Comment by amye** [comment]
Last thing: "Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)" ?

**Comment by amye** [comment]
Also, trademarks: we have agreements for both registered and non-registered. I don't have anything from you on that yet.

**Comment by salaxander** [comment]
@amye We've adopted FOSSA, is the ask to get the badge added to the README? I'll get the licensing doc over to you today. Sorry for the delay on that, I originally thought the only action there was to reference LF as the trademark owner in the license text.

**Comment by krook** [comment]
Hello Eraser team! I’ve invited your GitHub organization to the CNCF GitHub Enterprise account. 

Once you accept the invitation, we can then confirm `thelinuxfoundation` is an owner, and then onboard you to LFX Insights (which is a matter of adding an app, similar to adding the DCO bot) which uses read only, public data to drive the reports on the [Insights dashboard](https://insights.lfx.linuxfoundation.org/foundation/cncf).

That would mark these two checklist items as up-to-date and complete (and it supersedes the need to add Chris and I as owners):

- [ ] GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership while we onboard you to our GitHub Enterprise instance: <https://github.com/enterprises/cncf>
- [ ] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/> (This is a new one that was added to the onboarding template since this initial onboarding issue was opened)

You can learn more about Insights here:

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)

Please let me know if you have any questions about onboarding GHE and/or Insights.

**Comment by krook** [comment]
Thanks for accepting the GitHub Enterprise invitation.

CNCF staff can now add `thelinuxfoundation` as an organization owner and then install the Insights app on the org.

Please let me know if you have any questions or concerns before we do that @sozercan.

**Comment by sozercan** [comment]
thanks @krook! `thelinuxfoundation`, `caniszczyk`, and `krook` should be owners now in the org.

**Comment by krook** [comment]
Thanks @sozercan 

The LFX Insights onboarding task is now marked complete on the CNCF side.

Once the initial data load finishes, I'll share a link to your project-specific dashboard where you can explore dashboards and reports. It should be ready for you by the end of the week.

**Comment by krook** [comment]
@sozercan Insights data loading is complete. You can now check out the [Eraser-specific dashboard here](https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=eraser&repository=). 

Through the left nav, you can go through the Overview, Velocity, and Productivity dashboards. There is also a set of info on Contributors, Organizations, and Activities under the Reports section. All of them can be filtered by timeframe.

You can find [Insights documentation here](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current), file [tickets if something doesn't look right](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4?requestGroup=54) (v3 is in beta so any reports are very helpful), and [post public feedback at this forum topic](https://community.lfx.dev/t/lfx-insights-v3-feedback/2430).

**Comment by Cmierly** [comment]
Eraser has completed onboarding!
