### ISSUE TITLE
Adopting UTC as the Standard Time Reference for CNCF TOC and TAG Calendaring 🌐

### ISSUE THREAD

**Issue by anvega** [cncf/toc#1182]
As the CNCF community expands and embraces members from all corners of the world, it's important for us to foster an inclusive and welcoming environment. One subtle yet significant way we can achieve this is by addressing the markers that inadvertently convey a US-centric view of the world.

It's been observed that many members, especially those joining from regions outside of the US, often spend extra time converting time zones like Pacific and Eastern to the Universal Standard. To create a level playing field, where every member invests an equal amount of effort, I propose we consider transitioning to UTC as our standard reference time.

During the recent OSS Summit EU, I conducted a survey across different Linux Foundation organizations and projects for guidance. A predominant response was their preference to use UTC, especially in communities such as AGL and Yocto, which have substantial representation from Japan and Central Europe.

Admittedly, there will be an initial adjustment phase, especially for members in the US across various time zones, as well as the UK with GMT and British Summer Time. However, calendar tools are equipped to handle such transitions seamlessly. Another point to consider is the observation of daylight savings in various countries. Luckily, machines can easily handle these shifts for us.

On a related note, adopting UTC is a more holistic approach compared to merely categorizing meetings as North America or EMEA which I have been advocating in TAG Security to move away from. Such categorizations often inadvertently exclude regions like South America and APAC. By using UTC, we ensure inclusivity for all members, regardless of their geographical location, by which people's availability bounds are not strictly constrained, allowing them to participate whenever the time aligns conveniently for them. 

🌏🌍🌎

**Comment by mrbobbytables** [comment]
This is a great thing on paper, but speaking as someone that HAS advocated for this, AND implemented it..then had to roll-back because of the sheer amount of toil and friction it caused when rolling out to a large group, the additional work it creates winds up being an extreme net-negative for everyone, APAC members included. 

It works great in singleton instances where you know the meeting timeslot can work for the majority of people, and those that DO follow DST can continue to attend with the timeshift.

If you "pin" the meeting time to UTC, and those that DO use daylight savings time have the meeting "shift" for them frequently wind up not being able to attend because of back-to-back meetings and the rest of their meetings DO shift. Anecdotally this impacts the organizers the most. They tend to be the ones that have the most meetings. What winds up happening is they update the meeting the time to be the pre-dst time.

If you decide to keep the DST timeslot and update the meeting times 2x a year - it creates A LOT of work to update it everywhere. Using K8s as an example, there are 34 groups, and between those groups there are roughly 220 meetings a month generated from roughly 100~ recurring calendar meetings. In k8s, we have some automation to help us update the meeting times in different markdown files, but roughly each one of those meetings times is in at least 5 different locations. 

updates to sigs.yaml will update it in 2 other locations automatically (sig-list.md and the group's own README), other automation will pick it up to update k8s.dev.  Those updates are a PR that requires 2 people to sign off. Then you have to update all the entries in the various OTHER docs, like meeting notes etc. You wind up having to update times in hundreds of locations multiple times a year to keep things in sync.

If you have to send out any sort of updated calendar invites, there are some organizations that have calendar implementations that will ONLY update if there are comments sent with the calendar update (this took A LOT of effort to figure out why some people were not getting updates). Seriously, you'd think calendaring wouldn't be so hard these days, but it's still a huge friction point (cc @jberkus ).

In the end it created so much friction for EVERYONE, that it was deemed not worth it to continue.

That was a lot of bad without offering a solution, but here is what I can say HAS worked:
Let the groups determine the time designation that works best for the majority of their group, just make SURE that it links out to a good time converter service (I recommend http://www.thetimezoneconverter.com)

If the majority of attendees are in a tz that has DST, make sure they link it to something like ET or PT that 'follows' DST. 

I'm going to copy the TL;DR of the kubernetes date & time style guide below, but for a full break down you can read more here: [Style Guide - Dates & Times](https://github.com/kubernetes/community/blob/master/contributors/guide/style-guide.md#dates-and-times)

**Dates & Times**
- Format dates as `month day, year`. (December 13, 2018)
- When conveying a date in numerical form, use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) Format: `yyyy-mm-dd`.
- Use the 24 hour clock when referencing time.
- Times for single events (example: KubeCon) should be expressed in an absolute
  time zone such as Pacific Standard Time (PST) or Coordinated Universal Time
  (UTC).
- Times for reoccurring events should be expressed in a time zone that follows
  Daylight Savings Time (DST) such as Pacific Time (PT) or Eastern Time (ET).
- Supply a link to a globally available time zone converter service.
  - `http://www.thetimezoneconverter.com/?t=<TIME REFERENCE>&tz=<TZ REFERENCE>`

**Comment by anvega** [comment]
Insightful, @mrbobbytables. Thank you!
