### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Spiderpool

### ISSUE THREAD

**Issue by Cmierly** [cncf/toc#1225]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk - <project-onboarding@cncf.io> is the best email to send those to
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: <https://github.com/enterprises/cncf>
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to <projects@cncf.io>
- [x] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [ ] Book time with the team with <http://project-meetings.cncf.io>
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by weizhoublue** [comment]
the following has been done:

-  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/

- Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

- Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md

- Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/

- Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
-----> Spiderpool license: Apache 2.0 

- Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
-----> https://github.com/spidernet-io/community

- Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details).
Spiderpool channel:  https://cloud-native.slack.com/messages/spiderpool

- Is your project in its own separate neutral github organization?
-----> yes

-  GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
-----> DCO has been installed

-  GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
-----> refer the [spiderpool readme](https://github.com/spidernet-io/spiderpool)

-  OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en
-----> refer the [spiderpool badge on the readme](https://github.com/spidernet-io/spiderpool)

the following is ongoing:

- Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io/

- Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
-----> PR: https://github.com/cncf/foundation/pull/696

- Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork

- Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

- Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk - [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io) is the best email to send those to
-----> email has been already sent

-  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

-  GitHub: ensure thelinuxfoundation, caniszczyk, and krook are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: https://github.com/enterprises/cncf

- Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).

- Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)

**Comment by weizhoublue** [comment]
maintainer mail list

| name  |  github ID | email |
| ----|----|------|
| Weizhou Lan | github ID is weizhoublue | email: [weizhou.lan@outlook.com](mailto:weizhou.lan@outlook.com) |
| Yan Kai | github ID is yankay | email: [yankaycom@gmail.com](mailto:yankaycom@gmail.com) |
| Haifeng Yao | github ID is windsonsea | email: [haifeng.yao@daocloud.io](mailto:haifeng.yao@daocloud.io) |
| Qifeng Guo | github ID is cyclinder | email: [kuocyclinder@gmail.com](mailto:kuocyclinder@gmail.com) |
| Kun Wu | github ID is Icarus9913 | email: [icaruswu66@qq.com](mailto:icaruswu66@qq.com) |
| Tao yang | github ID is ty-dc | email: [tymysuperman@gmail.com](mailto:tymysuperman@gmail.com) |

**Comment by weizhoublue** [comment]
I set up the [FOSSA for spiderpool](https://app.fossa.com/projects/git%2Bgithub.com%2Fspidernet-io%2Fspiderpool/refs/branch/main/0ac439b243994490a3bd12572303cc7218edbb5d) 
I am not assure whether it meets the requirement or not, please help check

**Comment by Stella0621** [comment]
-  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

Hi @Cmierly，I'm sorry  I couldn't find the repository address to submit the trademark agreement. Where should I submit the filled-out trademark agreement? Or should I send it to you via email?

**Comment by amye** [comment]
> * Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
> 
> Hi @Cmierly，I'm sorry I couldn't find the repository address to submit the trademark agreement. Where should I submit the filled-out trademark agreement? Or should I send it to you via email?

A signed PDF can go to project-onboarding@cncf.io!

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://spiderpool.devstats.cncf.io) added - affiliations will be researched in January.

**Comment by lukaszgryglicki** [comment]
The project was added to [projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1) dashboard.

**Comment by Stella0621** [comment]
Hi @amye @lukaszgryglicki , I have sent the filled spiderpool-trademark agreement email to [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io), please check, thank you. And What should we do next?

**Comment by amye** [comment]
> Hi @amye @lukaszgryglicki , I have sent the filled spiderpool-trademark agreement email to [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io), please check, thank you. And What should we do next?

In progress, thank you!

**Comment by krook** [comment]
Hi @weizhoublue and @Stella0621,

- [ ] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>

For this task, we will use the GitHub `thelinuxfoundation` id to install a read-only app on your organization (similar to the DCO bot) which uses public data to drive the reports on the [Insights dashboard](https://insights.lfx.linuxfoundation.org/foundation/cncf).

Do you have any questions about Insights before we do that?

You can learn more about Insights here:

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)

**Comment by weizhoublue** [comment]
> Insights dashboard

Hi, @krook , sorry for late response. That is great, LGTM

**Comment by krook** [comment]
The LFX Insights onboarding task is now marked complete on the CNCF side.

Once the initial data load finishes, I'll share a link to your project-specific dashboard where you can explore dashboards and reports. It should be ready for you by the end of the week.

**Comment by weizhoublue** [comment]
> The LFX Insights onboarding task is now marked complete on the CNCF side.
> 
> Once the initial data load finishes, I'll share a link to your project-specific dashboard where you can explore dashboards and reports. It should be ready for you by the end of the week.

That sounds great, many thanks

**Comment by Cmierly** [comment]
Hi @weizhoublue !
There are only a few quick tasks left! Once those are done, you will be fully onboarded!

**Comment by weizhoublue** [comment]
> Hi @weizhoublue !
> There are only a few quick tasks left! Once those are done, you will be fully onboarded!

 Hi @Cmierly 
thanks for reminding
BTW, all staffs are on holiday owing to the Spring Festival in China, from 9 to 17 this month. We will promote the process after the holiday


- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
       ---- We have read and understood it, are there any actions we miss ?

- [x] Insights: add to LFX Insights https://insights.v3.lfx.linuxfoundation.org/
      ----- it seems to be finished, and available at https://insights.lfx.linuxfoundation.org/foundation/cncf/overview?project=spiderpool&repository=

- [ ] Marketing: update relevant intro + slide decks
     ------ what action should I take for this one ?

- [ ] Events: update CFP + Registration + CFP Area forms
     ------ what action should I take for this one ?

- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
         ---- We have read it

- [ ]  CNCF Welcome Email Sent to confirm maintainer list access
       ----- there is no action I should take, right ?

- [ ]  Book time with the team with http://project-meetings.cncf.io/
         ---- I will promote the process after the holiday

- [ ]  Create space for meetings/events on https://community.cncf.io/, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
         ---- I will promote the process after the holiday

**Comment by weizhoublue** [comment]
hi @Cmierly 
for the meeting '30 Minutes w/ CNCF Projects Team', what is the main subject of the meeting , and should I prepare something special in advance ? 
thanks

**Comment by Cmierly** [comment]
@weizhoublue This meeting is optional and the time will be for you and your team to ask questions, discuss any concerns or resolve any roadblocks you may have in completing the onboarding tasks.

No in-depth work required on your part!

**Comment by Stella0621** [comment]
Hi @Cmierly, I have noticed that the following six items have not been marked as on your end:
- [ ] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction

- [ ] Marketing: update relevant intro + slide decks

- [ ] Events: update CFP + Registration + CFP Area forms

- [ ] CNCF Welcome Email Sent to confirm maintainer list access

- [ ]  Book time with the team with http://project-meetings.cncf.io/

- [ ]  Create space for meetings/events on https://community.cncf.io/, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)

We don't have any further updates or submissions to make regarding these matters. If the processes are complete, would you kindly update the status by ticking off the items  listed? Should there be anyting else required from us, please inform us at your earliest convenience. 
Thanks.

**Comment by Cmierly** [comment]
Hi @Stella0621 !
If your team has no further questions for us and doesn't need to meet, we can close your onboarding tasks!

**Comment by Stella0621** [comment]
Hi, @Cmierly ,
we have no further questions or meeting, you can close the onboarding tasks.
Thanks.

**Comment by Cmierly** [comment]
Thank you!
Spiderpool is now fully onboarded!
