### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] easegress

### ISSUE THREAD

**Issue by Cmierly** [cncf/toc#1226]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk - <project-onboarding@cncf.io> is the best email to send those to
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: <https://github.com/enterprises/cncf>
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to <projects@cncf.io>
- [x] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [ ] Marketing: update relevant intro + slide decks
- [ ] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [ ] Book time with the team with <http://project-meetings.cncf.io>
- [ ] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) 
- [x] Adopt a static application security testing  tool like [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://easegress.devstats.cncf.io) added - affiliations will be researched in January.

**Comment by lukaszgryglicki** [comment]
The project was added to [projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1) dashboard.

**Comment by xxx7xxxx** [comment]
Update status

* [x]  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
* [x]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
* [x]  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
* [x]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
* [x]  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
* [x]  Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist -> **Easegress uses Apache 2.0**
* [x]  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
* [ ]  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
---> I exported easegress channel in OpenMegaEase, and I have already created easegress channel in CNCF slack. Please help import corresponding data[1] into it.
* [x]  Is your project in its own separate neutral github organization?
 Yes: https://github.com/easegress-io/easegress
* [x]  Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
---> https://github.com/cncf/landscape/pull/3670
* [x]  Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
---> https://github.com/cncf/foundation/pull/705
* [ ]  Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
-> We're designing all of them.
* [x]  Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63
---> Easegress does not have a dedicated domain.

Things that CNCF will need from the project:

* [x]  Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk - [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io) is the best email to send those to
---> Sent from longdeqidao@gmail.com
* [x]  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
---> Easegress does not have trademark.
* [x]  GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: https://github.com/enterprises/cncf
* [x]  GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
---> Enabled DCO
* [x]  GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
---> See https://github.com/easegress-io/easegress?tab=readme-ov-file#contributing
* [x]  Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
---> We don't have dedicated domain for Easegress, but we host its page in https://megaease.com/easegress/ . Can we not put footer in it?
* [x]  Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
---> Easegress does not have website analytics.
* [x]  OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en
---> https://github.com/easegress-io/easegress?tab=readme-ov-file#easegress--

## Reference

[1] https://drive.google.com/drive/folders/1qSC3e8q5w7IpbvTYFLSEWFLVtV4C5Ydx

**Comment by xxx7xxxx** [comment]
@Cmierly Thanks a lot! Is there anybody to help migrate the Slack channel data?

**Comment by xxx7xxxx** [comment]
@amye I have sent maintainers' emails (longyun@megaease.com) to project-onboarding@cncf.io . But I can't use the email to log in CNCF Service Desk for now.

**Comment by xxx7xxxx** [comment]
A dedicated service desk ticket was created.

**Comment by xxx7xxxx** [comment]
Artworks PR opened https://github.com/cncf/artwork/pull/454

**Comment by xxx7xxxx** [comment]
Slack channel migration was done. The next thing would be finishing items of `Things that the CNCF will do or help the project to do`. FYI

**Comment by RobertKielty** [comment]
I added the FOSSA team and invited the maintainer group to become a FOSSA team member. 

@xxx7xxxx and I worked together to get the [easegress-io org](https://github.com/easegress-io/) repos scanned by FOSSA.

cc @krook

**Comment by krook** [comment]
Hi @xxx7xxxx,

- [ ] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>

For this task, we will use the GitHub `thelinuxfoundation` id to install a read-only app on your organization (similar to the DCO bot) which uses public data to drive the reports on the [Insights dashboard](https://insights.lfx.linuxfoundation.org/foundation/cncf).

Do you have any questions about Insights before we do that?

You can learn more about Insights here:

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)

**Comment by xxx7xxxx** [comment]
@krook No problem, please do that.

**Comment by RobertKielty** [comment]
Re-sent out an Snyk invite to the maintainer group.io email addr for the project. We had problems last week with completing this task my focus today will be getting this working for easegress.

**Comment by RobertKielty** [comment]
I went through a couple of iterations of sending out the Snyk invite to @xxx7xxxx but all have failed.

I am sending out the invite to the groups email address and the Snyk invite link is not being accepted.

What we tried to get it to work was we added the groups email addr to @xxx7xxxx GH profile but the invite was still rejected. Next step here will be to log a call with Snyk support to find out why these specific invites are being rejected and see what we can from there.

**Comment by xxx7xxxx** [comment]
Except for the Synk, what do I need to do to finish the onboarding? @Cmierly

**Comment by RobertKielty** [comment]
Just met with @xxx7xxxx. 

Last week, I had setup the easegress org in Snyk, but we had an issue with the Snyk invitation being sent to @xxx7xxxx

The invite issue was still happening today, and @xxx7xxxx logged a support call with Snyk cc'ing me.

As a workaround, @xxx7xxxx provided me with an alternative email addr and that invitation worked!

The donated repo is being scanned now by Snyk.

**Comment by krook** [comment]
The LFX Insights onboarding task is now marked complete on the CNCF side.

Once the initial data load finishes, I'll share a link to your project-specific dashboard where you can explore dashboards and reports. It should be ready for you by the end of the week.

**Comment by xxx7xxxx** [comment]
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
---> We have read through the page.

- [ ] Book time with the team with http://project-meetings.cncf.io/
---> Is it a mandatory thing to do? What topics need we prepare?

- [ ] Create space for meetings/events on https://community.cncf.io/, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
---> Should I apply a request on Service Desk to get help to create a community space?

And BTW, I have updated my email address from longyun@megaease.com to longdeqidao@gmail.com . I can't log in with the newest one, could you please update it on service desk?

**Comment by xxx7xxxx** [comment]
@Cmierly Thanks! Invitation accepted.

**Comment by Cmierly** [comment]
easegress has completed onboarding!
