### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] kube-burner

### ISSUE THREAD

**Issue by Cmierly** [cncf/toc#1230]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk - <project-onboarding@cncf.io> is the best email to send those to
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: <https://github.com/enterprises/cncf>
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to <projects@cncf.io>
- [x] OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Book time with the team with <http://project-meetings.cncf.io>
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by rsevilla87** [comment]
Hi @Cmierly, first of all thanks for accepting kube-burner as a CNCF sandbox project. I'm currently going over the checks you've sent, so expect future questions/doubts from me :)

Along with the project onboarding we've the intention of migrating the project from the `cloud-bulldozer` organization, which contains other projects not related with kube-burner, to a new `kube-burner` organization, that's to say the project's URL will be migrated from https://github.com/cloud-bulldozer/kube-burner to https://github.com/kube-burner/kube-burner

I wonder if there's any action that should take into account to perform this migration safely from an onboarding perspective.

Thanks

**Comment by amye** [comment]
That's the "Is your project in its own separate neutral github organization?" - let us know when it's complete!

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://kubeburner.devstats.cncf.io) added - affiliations will be researched in January.

**Comment by lukaszgryglicki** [comment]
The project was added to [projects health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1) dashboard.

**Comment by rsevilla87** [comment]
> That's the "Is your project in its own separate neutral github organization?" - let us know when it's complete!

Done, we just moved kube-burner to its own separate organization https://github.com/kube-burner/kube-burner

**Comment by rsevilla87** [comment]
Progress update:

* [x]  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction 
* [ ]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/ 
* [ ]  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy 
* [ ]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md 
* [ ]  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ 
* [ ]  Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist 
* [ ]  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/ 
* [ ]  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details) 
* [ ]  Is your project in its own separate neutral github organization? 
* [ ]  Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io 
* [ ]  Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it 
* [ ]  Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork 
* [ ]  Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63  

Things that CNCF will need from the project:

* [ ]  Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk - [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io) is the best email to send those to 
* [ ]  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements 
* [ ]  GitHub: ensure `thelinuxfoundation`, `caniszczyk`, and `krook` are added as initial org owners, this helps us make sure we have continuity of GH ownership that we will onboard to our GitHub Enterprise instance: https://github.com/enterprises/cncf 
* [ ]  GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project 
* [ ]  GitHub: ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub 
* [ ]  Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub). 
* [ ]  Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io) 
* [ ]  OpenSSF Best Practices Badge: Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en

**Comment by rsevilla87** [comment]
FOSSA as been enabled in project

**Comment by amye** [comment]
> Hey @Cmierly , I've doubts on the trademark transfer, we do not have a registered trademark currently, do we have to send this document https://github.com/cncf/foundation/blob/main/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf somewhere?

Yes! Drop it into project-onboarding@cncf.io and we'll help!

**Comment by krook** [comment]
Hi kube-burner team,

- [ ] Insights: add to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>

For this task, we will use the GitHub `thelinuxfoundation` id to install a read-only app on your organization (similar to the DCO bot) which uses public data to drive the reports on the [Insights dashboard](https://insights.lfx.linuxfoundation.org/foundation/cncf).

Do you have any questions about Insights before we do that?

You can learn more about Insights here:

- [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)

**Comment by rsevilla87** [comment]
> Hi kube-burner team,
> 
>     * [ ]  Insights: add to LFX Insights https://insights.v3.lfx.linuxfoundation.org/
> 
> 
> For this task, we will use the GitHub `thelinuxfoundation` id to install a read-only app on your organization (similar to the DCO bot) which uses public data to drive the reports on the [Insights dashboard](https://insights.lfx.linuxfoundation.org/foundation/cncf).
> 
> Do you have any questions about Insights before we do that?
> 
> You can learn more about Insights here:
> 
>     * [Insights documentation](https://docs.linuxfoundation.org/lfx/insights/v3-beta-version-current)

understood, go ahead

**Comment by krook** [comment]
The LFX Insights onboarding task is now marked complete on the CNCF side.

Once the initial data load finishes, I'll share a link to your project-specific dashboard where you can explore dashboards and reports. It should be ready for you by the end of the week.

**Comment by rsevilla87** [comment]
Hi  @Cmierly, FOSSA scanning is adopted https://app.fossa.com/projects/git%2Bgithub.com%2Fkube-burner%2Fkube-burner?utm_source=share_link

Im hoping to send trademark transfer document soon. The other missing items are now from the `Things that the CNCF will do or help the project to do:` section

Thanks!

**Comment by vishnuchalla** [comment]
@Cmierly can we get some clarity on these two items please? On where we can find those slide templates and CFP forms.
```
 Marketing: update relevant intro + slide decks
 Events: update CFP + Registration + CFP Area forms
```
Also requesting access to check mark the boxes that we have completed from the description.

**Comment by Cmierly** [comment]
@vishnuchalla 
Hi!
Those two tasks are handled on our end. 
I cannot grant access to check off on the official task list as it is something we must do on our end. I can check them off for you once you confirm the completed tasks

**Comment by vishnuchalla** [comment]
> @vishnuchalla Hi! Those two tasks are handled on our end. I cannot grant access to check off on the official task list as it is something we must do on our end. I can check them off for you once you confirm the completed tasks

@Cmierly Thanks for the clarification.

**Comment by amye** [comment]
Welcome onboard!
