### ISSUE TITLE
[ARCHIVE] OpenEBS

### ISSUE THREAD

**Issue by amye** [cncf/toc#1250]
- [x] TOC vote to archive passed
- [x] Move logo to archived on CNCF.io	
- [x] Remove from landscape		
- [x] Archive maintainers mailing list	
- [x] Remove ML from maintainers@ mailing group
- [x] Remove/Archive on maintainers.cncf.io (https://github.com/cncf/foundation/pull/825)
- [x] Remove logo from all slide decks	
- [x] Remove logo from event sites	
- [x] Move logo to archived in artwork https://github.com/cncf/artwork/pull/484
- [x] Archive DevStats (or archive?)	
- [x] Notify Speakers team to remove from CFPs	
- [x] Remove from service desk or archive	
- [x] Remove from CNCF store
- [x] Remove from [CLOMonitor data](https://raw.githubusercontent.com/cncf/clomonitor/main/data/cncf.yaml)

**Comment by edrob999** [comment]
@amye On the YouTube video of the TOC meeting 2024-01-16 discussing OpenEBS archiving, there was an issue raised about the OpenEBS Trademark, I believe you or Michael were going to contact DataCore. I work for DataCore - and want to make sure we resolve this. Ed

**Comment by caniszczyk** [comment]
@edrob999 the trademark usage examples here should be easy to follow to correct any issues

https://www.linuxfoundation.org/legal/trademark-usage

**Comment by edrob999** [comment]
Thanks @caniszczyk. I reviewed the guidelines. I believe we (or others in the community) can include the term “OpenEBS” as a descriptive part of a commercial product name, following the same pattern where many commercial organizations use the CNCF trademarked word “Kubernetes” as part of their product name. (e.g. Amazon, Azure, Google, IBM etc).

**Comment by edrob999** [comment]
@caniszczyk Sometimes it can be better to discuss in person. I'm at KubeCon Paris - we have a DataCore booth in the exhibition hall, if you or anyone else can make time to talk, please come to our booth.

**Comment by caniszczyk** [comment]
I'm happy to chat at kubecon, reach out over email?

@edrob999 that is not true unless you have a conformance program where the CNCF board has approved the usage of the name in a product, e.g., https://github.com/cncf/k8s-conformance
https://github.com/cncf/k8s-conformance/blob/master/terms-conditions/Certified_Kubernetes_Terms.md

This is done because conformance programs ensure neutrality and have multiple vendors involved.

By default, everyone falls under https://www.linuxfoundation.org/legal/trademark-usage

Correct: <your product name> for <The Linux Foundation mark>

Correct: <your product/company name> plug-in for <The Linux Foundation mark>

Correct: <your product name> compatible with <The Linux Foundation mark>

Correct: <your product name> for use with <The Linux Foundation mark>

Correct: Quick Start for <The Linux Foundation mark> by <your company name>

Correct: <non-trademarked industry term> Day featuring <The Linux Foundation mark>

Correct: <non-trademarked industry term> Day with <The Linux Foundation mark>

Correct: <non-trademarked industry term> Day including <The Linux Foundation mark>

Incorrect: <The Linux Foundation mark> <your product name>

Incorrect: <The Linux Foundation mark> by <your company name>

Incorrect: <The Linux Foundation mark> – <your product name>

Incorrect: <your product/company name> – <The Linux Foundation mark>

Incorrect: <The Linux Foundation mark> Quick Start by <your company name>

Incorrect: <The Linux Foundation mark> Day

Incorrect: <The Linux Foundation mark> Day by <your company name>

Incorrect: <non-trademarked industry term> Day brought to you by <The Linux Foundation mark>

**Comment by edrob999** [comment]
@caniszczyk: thx, I'll reach out over mail, and set up time to discuss

**Comment by mrbobbytables** [comment]
All tasks have been completed, going to go ahead and close this out :+1:
