### ISSUE TITLE
Thoughts on numbering convention for uid/gid values

### ISSUE THREAD

**Issue by mattrpav** [cncf/toc#127]
One of the challenge with shipping 'ready-to-go' containers (containers that do not need further modification) is the assignment of uid/gid values to run as non-root-- especially for containers that use a volume. User namespaces look to address the stateless use case, but there is a gap for stateful services (and vm-managed by k8s) to address the filesystem uid+gid collision issue.

I'm curious to get feedback on a convention of leveraging [IANA Private Enterprise Numbers](https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers) as the basis for a registry of 3rd party uid+gid values. I recognize that previous efforts to reserve tcp port numbers was severely limited due to the small range allowed. However, with ~4B available UID's, it seems there would be enough head room to consider the ability for CNCF implementations to (optionally) reserve UID/GID range based on a convention.

Something along the lines of:
0 - 2,000,000,000 (reserved for local user and group id)
2,000,000,000 - UID MAX (2,000,000,000 + PEN number for 3rd parties)

Example uids:
2,000,000,002 --> 'ibm' uid / gid
2,000,000,003 --> 'cmu' uid / gid
etc..

**Comment by justincormack** [comment]
4 billion is hardly any, sadly (Posix should allow 64 bit uids really). I don't quite understand how giving IBM a single uid would help. The problem is that you want each container on a host to use a different uid ideally, but also to know what it will be up front when there is no real coordination mechanism.

**Comment by mattrpav** [comment]
@justincormack volumes can span hosts (and be shared between container instances), in those use cases, it is prudent to know the uid's ahead of time.

You do bring up a good point about IBM needing a bunch of ids.. perhaps tweaking the approach that the PEN numbers are used for the user namespace value. This would allow IBM to "own" the uid+gid space within its namespace, and follows how PEN numbers are used in SNMP and LDAP, where the PEN number is a sub-domain delimiter of sorts and the organization manages the child numbering.

**Comment by fatherlinux** [comment]
@mattrpav, @justincormack brought up another problem. What happens when you run the exact same piece of IBM software three times on the same host? There will still be collisions. That's why shiftfs or something like that, which can dynamically map uids in the container to dynamically chosen uids outside the container makres so much sense.

Then every software vendor is free to choose whatever they want in the container.
