### ISSUE TITLE
Add Armenian translation of the CNCF Cloud Native Definition v1.0

### ISSUE THREAD

**Issue by shantdashjian** [cncf/toc#1280]
In order to increase access to cloud native concepts among Armenian-speaking software professionals
As a developer
I want to see an Armenian translation of the CNCF Cloud Native Definition v1.0

**Comment by Riaankl** [comment]
@shantdashjian thank you for are you suggestion. Do you speak Armenian and work with a Armenian speaking developer community?

Then I would propose you start with the community to create a translation that they can agree to reflect the correct translation of [Cloud Native Technology](https://glossary.cncf.io/cloud-native-tech/) and other terminology.

We already have translations in 14 languages all driven by the community at https://github.com/cncf/glossary.

I would propose to close the issue here and create a new issue in the glossaty repo.
If you are unsure where to start I can put you in contact with the person that started the Turkish translation section.

**Comment by aliok** [comment]
What I understand is that @shantdashjian wants to have the Cloud Native Definition (https://github.com/cncf/toc/blob/main/DEFINITION.md) translated to Armenian.

I don't know what the procedure for translating that document.
For example, I see the Turkish translation was added in this PR, without much context: https://github.com/cncf/toc/pull/656

However, overall, if you're interested in starting a team for localizing the [CNCF Glossary](https://glossary.cncf.io/) to Armenian, here's how the Turkish localization team proceeded as an example:
- I created a discussion in Glossary repository to gather interest for localization: https://github.com/cncf/glossary/discussions/2108
- I promoted that discussion on social media.
- Once there's enough interest, I followed the ["Initiating a new localization team"](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#initiating-a-new-localization-team) and created an issue: https://github.com/cncf/glossary/issues/2123

Then we started working on the localization :) Turkish localization went live recently after 8 months of work: https://glossary.cncf.io/tr/

I hope this helps.
