### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Kubean

### ISSUE THREAD

**Issue by jeefy** [cncf/toc#1301]
Welcome to CNCF Project Onboarding!

This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.

We would like to complete onboarding within one month of acceptance.

**From the project side, please ensure that:**

- [x] You understand the project proposal process and requirements: <https://github.com/cncf/toc/blob/main/process/README.md>
- [x] You understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] You ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] You review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] You understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] You understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Your project is working on written, open governance. See <https://contribute.cncf.io/maintainers/governance/>
- [x] Your Slack channels are migrated to the Kubernetes or CNCF Slack workspace. See <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Your project in its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account.
- [x] You submit a pull request to add your project as a Sandbox project to <https://landscape.cncf.io>
- [x] You create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] You submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] You transfer your domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

**Things that CNCF will need from the project:**

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and Service Desk - <project-onboarding@cncf.io> is the best email to send those to
- [x] Transfer any trademark and logo assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project
- [x] Ensure that [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines for the README file of your project on GitHub).
- [x] Transfer website analytics to <projects@cncf.io>
- [x] Start on an OpenSSF Best Practices Badge <https://bestpractices.coreinfrastructure.org/en>

**Things that the CNCF will do or help the project to do:**

- [x] Add your project to DevStats <https://devstats.cncf.io/>
- [x] Add your project to LFX Insights <https://insights.v3.lfx.linuxfoundation.org/>. This is a read-only app added to the GitHub organization once your project is in the CNCF GitHub Enterprise account and we add `thelinuxfoundation` as an organization owner.
- [x] Update relevant marketing intros and slide decks
- [x] Update event call for papers, registration, and CFP area forms
- [x] Confirm maintainers have read about what's available through the Service Desk <https://www.cncf.io/services-for-projects/>
- [x] CNCF sends a welcome email to confirm maintainer list access
- [x] Book time with the team using <http://project-meetings.cncf.io>
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
DevStats [instance](https://kubean.devstats.cncf.io) added, adding to "All CNCF" [instance](https://all.devstats.cncf.io) in progress, researching affiliations in progress.

**Comment by lukaszgryglicki** [comment]
Project added to `All CNCF` DevStats [instance](https://all.devstats.cncf.io), also included in projects health dashboards [here](https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Kubean) and [there](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1).

**Comment by tu1h** [comment]
the maintainer mail below has been emailed to [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io)

| Name          | Github ID  | Email                                                         |
|---------------|------------|---------------------------------------------------------------|
| Erik Jiang    | ErikJiang  | [bo.jiang@daocloud.io](mailto:bo.jiang@daocloud.io)           |
| Guangli Bao   | tukwila    | [2509160562@qq.com](mailto:2509160562@qq.com)                 |
| Nathan Jiang  | hangscer8  | [hangscer@hotmail.com](mailto:hangscer@hotmail.com)           |
| Lihai Tu      | tu1h       | [tuuwtu1@gmail.com](mailto:tuuwtu1@gmail.com)                 |
| Michael Yao   | windsonsea | [haifeng.yao@daocloud.io](mailto:haifeng.yao@daocloud.io)     |
| Xiao Zhang    | wawa0210   | [xiaozhang0210@hotmail.com](mailto:xiaozhang0210@hotmail.com) |
| Peter Pan     | panpan0000 | [peter.pan@daocloud.io](mailto:peter.pan@daocloud.io)         |
| Kai Yan       | yankay     | [yankaycom@gmail.com](mailto:yankaycom@gmail.com)             |
| Shaolong Qin  | KubeKyrie  | [shaolong.qin@daocloud.io](mailto:shaolong.qin@daocloud.io)   |
| Panyintian Fu | FloatXD    | [1416297674@qq.com](mailto:1416297674@qq.com)                 |

**Comment by ErikJiang** [comment]
### 😄 the following has been done:

#### From the project side, please ensure that:

- [x] You understand the project proposal process and requirements: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
- [x] You understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] You ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] You review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- [x] You understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
- [x] You understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
  * Kubean license: Apache 2.0
- [x] Your project is working on written, open governance. See https://contribute.cncf.io/maintainers/governance/  (TODO 修改)
  * https://github.com/kubean-io/kubean/blob/main/GOVERNANCE.md
- [x] Your Slack channels are migrated to the Kubernetes or CNCF Slack workspace. See https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
  * Kubean channel: https://cloud-native.slack.com/messages/kubean
- [x] Your project in its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account.
- [x] You submit a pull request to add your project as a Sandbox project to https://landscape.cncf.io/
- [x] You create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it
- [x] You submit a pull request to https://github.com/cncf/artwork with your artwork
https://github.com/cncf/artwork/pull/474
- [x] You transfer your domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63
  * Kubean has no domain, it utilizes the GitHub pages as the website server.

#### Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and Service Desk - [project-onboarding@cncf.io](mailto:project-onboarding@cncf.io) is the best email to send those to
- [x] Transfer any trademark and logo assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
  * kubean has no registered trademarks
Accept the invite to join the CNCF GitHub Enterprise account. We'll then add the linuxfoundation as an organization owner to ensure neutral hosting of your project
- [x] Ensure that [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
  * DCO has been installed
- [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
  * done. refer to the [kubean readme](https://github.com/kubean-io/kubean?tab=coc-ov-file)
- [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines for the README file of your project on GitHub).
  * ready, refer to [website](https://kubean-io.github.io/kubean/en/#others)
- [x] Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io)
  * there is no Website Analytics for kubean
- [x] Start on an OpenSSF Best Practices Badge https://bestpractices.coreinfrastructure.org/en
  * done. refer to the [kubean badge on the readme](https://github.com/kubean-io/kubean)

#### Things that the CNCF will do or help the project to do:

- [x] Add your project to DevStats https://devstats.cncf.io/
- [ ] Add your project to LFX Insights https://insights.v3.lfx.linuxfoundation.org/. This is a read-only app added to the GitHub organization once your project is in the CNCF GitHub Enterprise account and we add thelinuxfoundation as an organization owner.
- [ ] Update relevant marketing intros and slide decks
- [ ] Update event call for papers, registration, and CFP area forms
- [ ] Confirm maintainers have read about what's available through the Service Desk https://www.cncf.io/services-for-projects/
- [ ] CNCF sends a welcome email to confirm maintainer list access
- [ ] Book time with the team using http://project-meetings.cncf.io/
- [ ] Create space for meetings/events on https://community.cncf.io/, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)
  * I set it up already, [link](https://app.fossa.com/projects/git%2Bgithub.com%2Fkubean-io%2Fkubean/refs/branch/main/039b56cbbb9d2b494bfe49daf1538f9481d41a81/preview)

**Comment by krook** [comment]
Just sent an invite for Kubean to join the CNCF GitHub Enterprise. With that, we can then do the LFX Insights onboarding step.

**Comment by Cmierly** [comment]
The checklist has been updated and is current as of today!

**Comment by ErikJiang** [comment]
hi @krook, Kubean has received the invitation and has joined CNCF GitHub Enterprise.

**Comment by krook** [comment]
> hi @krook, Kubean has received the invitation and has joined CNCF GitHub Enterprise.

Great, we can now start the LFX Insights onboarding step. I'll let you know when it's done.

**Comment by ErikJiang** [comment]
@krook , 🤝 thanks a lot.

**Comment by ErikJiang** [comment]
😊 Hi @Cmierly, the [OpenSSF best practices badge](https://www.bestpractices.dev/en/projects/6263) for [kubean](https://github.com/kubean-io/kubean) has been updated.

**Comment by ErikJiang** [comment]
😀 Hello @Cmierly, would you mind checking if we have missed anything regarding the tasks for this onboarding?

**Comment by krook** [comment]
@ErikJiang looks like all the tasks for your project to do are complete. Only things left are on our side 👍🏼

**Comment by krook** [comment]
> The final task is to set up time with the projects team, but we know that Calendly link is currently broken. Stand by while we fix that.

The Calendly link is now fixed. @ErikJiang please go ahead and find a time that works for you to meet with the project team.

**Comment by ErikJiang** [comment]
🤝 Hello @krook, thank you for your efforts. What is the topic of this meeting? Is it mandatory to attend?

**Comment by Cmierly** [comment]
@ErikJiang 
Hi! The meeting isn't mandatory and is usually dedicated time for the project team to ask the CNCF team any questions they might have. Since Kubean is done with all other onboarding tasks, I'll close out the onboarding ticket but the option to book time will always be there!

Congrats on finishing onboarding!
