### ISSUE TITLE
Clarify that Sandbox Annual Review is no longer used

### ISSUE THREAD

**Issue by bridgetkromhout** [cncf/toc#1404]
A colleague asked me about filing their project's Sandbox Annual Review. I went on a journey of broken-link discovery and found this:

- Sandbox Annual Review in its previous manual form is no longer required: https://github.com/cncf/toc/issues/1123#issuecomment-2059402876
- Instead, insights are planned to be gleaned from automated reports: https://github.com/cncf/toc/issues/1134
- Any still-active references to this now-retired process need to be updated: https://github.com/search?q=org%3Acncf%20sandbox-annual&type=code
- One pending review should be merged or closed: https://github.com/cncf/toc/issues/931
- Optionally, move old reviews in https://github.com/cncf/toc/tree/main/reviews into the appropriate sub-folders.
- Adding a README to the formerly-used review folder (and removing the pull request template) will prevent others from needing to follow all these breadcrumbs in the future: https://github.com/cncf/toc/tree/main/reviews

**Comment by angellk** [comment]
Thank you @bridgetkromhout for bringing this to TOC attention - we will clean up and clarify!

**Comment by TheFoxAtWork** [comment]
The KubeDL Annual review has been closed: https://github.com/cncf/toc/issues/931#issuecomment-2313323814

**Comment by craigbox** [comment]
Could I ask _why_ sandbox annual review is no longer used?

**Comment by TheFoxAtWork** [comment]
@craigbox - of course.  Given the volume of projects, the TOC has opted to leverage automation, and while not every aspect of an annual review or project health can be assessed in an automated fashion, certain indicators do exist that may be leveraged to surface at-risk projects for a human review (health of review).  This will allow the TOC to apply limited resources to areas of the foundation that require attention, instead of applying those resources near-universally.

Additional background:
The annual reviews process required sandbox projects to complete the PR that provided a small portion of the information needed to ascertain the overall health and direction of the project. These were required annually for sandbox projects so the TOC would review them and "vote" to keep the project in the CNCF.  At the time the annual reviews were occurring, very few if any projects were voted out of the CNCF with several identified for archive.  However this annual review process consumed a substantial portion of the TOCs time for all projects in a sandbox status - impacting the TOC's ability to conduct due diligence and other responsibilities of the TOC. In an attempt to redistribute the workload, the TOC initially trialed delegation of annual reviews to TAGs (I believe you supported this through TAG Network) with the following expectations:
- Ensuring the review is consistent to the depth and quality of a meaningful review among all the TAGs
- Encouraging new contributions and participation within the TAGs by projects who have undergone an annual review (pay it forward)
- Elevating concerns or attention areas appropriately to unblock projects and provide support
- Establish a framework where iterative improvements can be made to this process as an outcome from our learnings in applying it

And the below Goal (focused on level of effort and time spent):
> In optimal circumstances, a contributor conducting a review spends at most maybe two hours tops on it. And Maintainers, no more than 2 hrs. These are not incubation due diligence activities.

As part of this trialing, reassessing the value of the sandbox annual review process, ascertaining viability of delegation to the TAGs, and to reducing the time spent by the TOC and maintainers in assessing sandbox projects post-acceptance was conducted. As these projects are intended to receive less support from CNCF than Incubating or Graduated, it stands to reason that the TOC should be more focused on incubating and graduated projects moving levels over annual reviews of sandbox. I believe at the time of the delegation to the TAGs, there were over 30 annual reviews that the TOC could not get through in a reasonable timeframe.

As part of the delegation to TAGs trialing, the TOC and TAGs learned the following:
- the existing sandbox annual review process did not provide sufficient information to appropriately ascertain the health and direction of these projects
- the existing process could be largely automated to reduce the level of effort on both maintainers, TOC, and TAGs and provide stronger indicators of project health and direction
- The TAGs, like the TOC, struggled to review the volume of PRs within a reasonable timeframe, many annual reviews originally assigned to TAGs as part of this effort were picked back up by the TOC to complete by the due date the group had defined previously which resulted in further delays for incubating and graduated projects.

During the trialing, areas of automation opportunity were defined and CNCF was engaged to identify modifications to existing tooling (devstats, clomonitor, and others) so that those data elements could be captured within those tools.  Ideally, so the TOC and any community member may ascertain the progress and health of any project in CNCF, sandbox or otherwise.  

At the time of those discussions with CNCF, the timeline to implement the requirements for automation was assumed to be approximately 6-9 months. The TOC opted to remove the sandbox annual review process in favor of automation, expecting the tooling referenced previously to be ready for use soon.  We've been requesting updates to the automation request periodically, and recently re-engaged Staff to reissue the original requirements to ensure our automation needs were met and we've engaged the End User TAB to reconcile potential disparities in the metrics and requirements requested between ourselves and the TAB.  Staff have provided a [recent update on the issue](https://github.com/cncf/toc/issues/1134#issuecomment-2176871869) with the current status. 

While the project to automate is taking longer than we originally anticipated, we are confident the recent re-engagement with Staff to implement the original requirements defined by the TOC will be completed soon and we may begin defining an appropriate and manageable schedule for the TOC to conduct reviews, efficiently.

In the interim, the TOC has requested Staff identify projects that appear inactive so we may conduct Health of reviews, regardless of their matriculation status. 

I hope this addresses your question.

**Comment by angellk** [comment]
Closing as complete - thanks again @bridgetkromhout !
