### ISSUE TITLE
Proposal to change TOC nomination process

### ISSUE THREAD

**Issue by mattklein123** [cncf/toc#323]
Per email thread here: https://lists.cncf.io/g/cncf-toc/message/3907

I propose we work towards a change to the nomination process (including a charter change if necessary) that would involve:

- Make all nominations public, with who / what org nominated the nominee.
- Some ability for a public comment period on the nominees. If there is concern around public comments, the comments could only go to those who will vote on the nominee (though I would greatly prefer everything be fully public).
This would apply to all types of seats (GB/TOC/End user/etc.).

I think this would vastly increase transparency and community trust in the process.

**Comment by snakescott** [comment]
Seems like by definition this would increase transparency, and increased transparency leading to increased trust seems common sense ish.

If anyone is opposed it would be interesting to understand what they see as the negatives. Would this process put undue burden on anyone? What concerns are there when it comes to public nominations and public comment? Perhaps they can be mitigated without needing to resort to private / no-comment process?

**Comment by monadic** [comment]
+1 excellent suggestion

**Comment by onlydole** [comment]
+1 - It'd be great to have this process be more transparent.

**Comment by baldwinSPC** [comment]
+1 for 100% transparency.

**Comment by dankohn** [comment]
If you’re aware of any, could you please provide references to any other open source election, maintainer selection, or similar open governance process where public comments on candidates was encouraged?

It seems like it might quickly devolve into the worst parts of high school, but I’m happy to see examples where this approach has worked well.

**Comment by hannibalhuang** [comment]
well for one: https://governance.openstack.org/election/

**Comment by onlydole** [comment]
I like how the Python organization manages their elections, too! You can see [nominees and nomination details](https://www.python.org/nominations/elections/).

**Comment by dankohn** [comment]
I haven’t commented on the proposal to make nominees public.

I don’t see in OpenStack or Python election materials where public comments are solicited and posted on the qualification of the nominees, which is @mattklein123‘s proposal, as I understand it. Could you please provide specific links?

**Comment by hannibalhuang** [comment]
> I haven’t commented on the proposal to make nominees public.
> 
> I don’t see in OpenStack or Python election materials where public comments are solicited and posted on the qualification of the nominees, which is @mattklein123‘s proposal, as I understand it. Could you please provide specific links?

For OpenStack there is always a [campaign phase](http://lists.openstack.org/pipermail/openstack-discuss/2019-February/002923.html) that asking candidates questions which in nature a demonstration of their qualification. However the qualification for entrance of the election is written in the governance although it is quite simple.

I think what @mattklein123 proposed here is not about the qualification for entrance but for the qualification of the TOC position. On that I think OpenStack has a good example of campaign period

**Comment by rootsongjc** [comment]
+1 100% transparency

**Comment by AevaOnline** [comment]
For a bit of history, the OpenStack Technical Committee  (equivalent of Kubernetes TOC) accepts self-nominations from any eligible candidate - any contributor active in the last 12mo, IIRC. There were never board-appointed seats on the TC. The initial TC was seeded from the PPB (project planning board), which itself was composed of the technical leaders of the first ~7 projects to spin out of Nova+Swift.

While all OS TC nominees are asked to answer a set of questions publicly, there was no open public comment period on the _people_ involved. It's nerve-wracking enough to run for election; now imagine, on top of that, asking everyone to air their opinions of you publicly? No thanks.... Like @dankohn raised already, such an invitation is likely to devolve rapidly and turn the election into nothing but a popularity contest.

This, in fact, was one of the oft-suggested drawbacks to OpenStack's TC (and PTL) election process -- in many ways, it _was_ a popularity contest with a fully-open electorate.  On the other hand, democratically-elected representation _is crucial_ to maintaining community trust, as are a transparent nomination and election process. Seeing how Kubernetes governance has differed from OpenStack's (which I was a part of from 2012-2016), I appreciate the differences in the CNCF/K8S model.

As a member of the Kubernetes Code of Conduct Committee, if anyone has concerns about a nominated candidate, I would encourage them to privately contact the CoCC with those concerns. Since the GB appoints TOC seats through a private nomination process today, this presents a catch-22 for which I do not have any solution to propose.

(( _insert gif of Princess Leia asking Obi-Wan for help_ ))

**Comment by dankohn** [comment]
>For OpenStack there is always a campaign phase that asking candidates questions which in nature a demonstration of their qualification. However the qualification for entrance of the election is written in the governance although it is quite simple.

Interesting. I looked at that thread but am having trouble figuring out:
* How many questions are asked?
* What % of applicants answer some or all of the questions?
* Is this process documented somewhere?

In any event, a public Q&A period seems substantially different than a "public comment period", where people are called on to comment on nominees.

**Comment by AevaOnline** [comment]
> > For OpenStack there is always a campaign phase that asking candidates questions which in nature a demonstration of their qualification. However the qualification for entrance of the election is written in the governance although it is quite simple.
> 
> Interesting. I looked at that thread but am having trouble figuring out:
>     * How many questions are asked?
>     * What % of applicants answer some or all of the questions?
>     * Is this process documented somewhere?

OS TC election process is documented in git, and there is a discussion period mentioned here as part of the campaigning process:
  https://opendev.org/openstack/election#tc-campaigning

**Comment by fungi** [comment]
> > For OpenStack there is always a campaign phase that asking candidates questions which in nature a demonstration of their qualification. However the qualification for entrance of the election is written in the governance although it is quite simple.
> 
> Interesting. I looked at that thread but am having trouble figuring out:
> 
>     * How many questions are asked?
> 
>     * What % of applicants answer some or all of the questions?
> 
>     * Is this process documented somewhere?

Links to the process documentation for technical election officials has already been provided, but to clarify: It's a voluntary and open-ended period wherein members of the community at large are encouraged to publicly ask candidates questions on the openstack-discuss mailing list about their platform statements, prior activities or more general questions on pressing topics of the day. This "campaigning" week is kicked off by an announcement to the ML:

http://lists.openstack.org/pipermail/openstack-discuss/2019-February/002897.html

Then campaigning discussion threads start up, and a majority of candidates tend to respond to most of the questions asked. There is no limit to the number of questions or who can ask them, and candidates are not strictly required to answer all (or any for that matter), but it provides an opportunity for the electorate to get to know the candidates a bit better in hopes of at least making it slightly less of a popularity contest and focusing more on policy-oriented opinions or other issues germane to the office for which they're running. An example:

http://lists.openstack.org/pipermail/openstack-discuss/2019-February/002923.html

As for other fully free and open projects not yet mentioned which have similar process, I encourage you to check out Debian Project Leader elections. They also have a campaigning period, though theirs lasts three weeks instead of one:

https://www.debian.org/devel/leader

**Comment by mattklein123** [comment]
Thanks everyone for the great discussion. I want to clarify a few points:

- The thing I care about most is nomination transparency. I see zero downside for making it very clear who got nominated by whom, especially for the GB appointed seats. This simple change would make it vastly more obvious when an organization is focused on self dealing, ignoring diversity, etc.
- Regarding public comments: I think it would greatly improve the process if the community was involved in the nomination/voting process in some way, even if they don't get to directly nominate or vote. I agree that a completely open public comment period might get out of control. If there are concerns about that (fair), I think there are middle ground proposals that would also work quite well. Some for thought and discussion: 
  - Have a mechanism for comments to be sent back to those that actually vote, but are not public. 
  - Do a variant of the Q&A that has been used and proposed above. I like this. In this way the questions can be moderated (TBD on the moderation process) and than all nominees have an option to answer and their answers are public.

re: a popularity contest: let's be honest that there is no easy answer here. I would argue that the current closed backroom process is just as much (if not more) of a popularity contest than a more open process. I think looking at the current composition of the TOC should make that pretty clear. I think we could actually *improve* this aspect by allowing less known nominees to to shine via a short "campaigning process" (community shows of support, Q&A answers, etc.)

**Comment by snakescott** [comment]
Could this ticket be split in to two, 

1. Nomination transparency
1. Everything else

Nomination transparency seems like a simpler and more binary suggestion, might be easier to act on if  decoupled from "additional community involvement"?

**Comment by sdake** [comment]
> Thanks everyone for the great discussion. I want to clarify a few points:
> 
> * The thing I care about most is nomination transparency. I see zero downside for making it very clear who got nominated by whom, especially for the GB appointed seats. This simple change would make it vastly more obvious when an organization is focused on self dealing, ignoring diversity, etc.

Hi @mattklein123. As the general developer population doesn't have an opportunity to see who nominates who from the GB, would you please provide a prior or existing examples of self-dealing? I'd really like to understand which vendors and other GB members are behaving in this way...

I get diversity may be ignored. Diversity should be baked into the charter. So should ethics...

**Comment by RichiH** [comment]
@dankohn The way Debian does Debian Project Leader  is roughly:

1. Any Debian Developer can nominate any other Debian Developer
2. Nominees publish a platform statement
3. Public discussion with and about nominees
4. All Debian Developers can cast a secret vote via Condorcet with Schulze method https://en.wikipedia.org/wiki/Condorcet_method#Schulze_method
5. Publish result and list of voters, keep votes secret

This would need to be trivially modified to allow for siloing of different nominating & voting groups to fit CNCF TOC process.

**Comment by amye** [comment]
Closing - we now make qualified nominees public as part of the process.
