### ISSUE TITLE
new process education

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#404]
Over the past year or so we've come really far in standing up the new SIGs (charter, chairs, meetings) and defining a transparent process for accepting projects into the CNCF at the different maturity levels (Sandbox, Incubation, Graduation). This has been a massive effort and I think we're finally at the point where we need to focus very heavily educating SIG chairs and the community at large.

What should this education process look like? Here are some thoughts I have and I would love to hear from the community:
- Take another pass at the process doc. Clarify any ambiguities now that we've gone through the process for multiple projects.
- Make sure the process doc is properly linked in the repo
- Figure out how to represent or link this information on the cncf website
- Maybe use a SIG chairs meeting to walk through the process and answer any questions the chairs may have? Perhaps, the SIG chairs and/or TOC members could also do a 10 min presentation at a SIG meeting in the next month to go through the same material with SIG members?

Open to more thoughts around this. Feedback welcome.
@amye - Is this something you'd be open to driving?

**Comment by amye** [comment]
Yes! Happy to look at this next week: we're already planning to move the TOC + SIG-Chairs meeting to the 3rd Tuesday of the month.

**Comment by amye** [comment]
Working on a PR for a README to come into that repo, but a question has come up as I review: 

There are two different project proposal templates: 
https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#project-proposal-requirements 
AND  
https://github.com/cncf/toc/pull/361 

We should review and make this more clear because this is definitely an ambiguity in the proposal process!

**Comment by amye** [comment]
PR for README for review/comments/suggestions: https://github.com/cncf/toc/pull/429
