### ISSUE TITLE
[PROJECT ONBOARDING] Parsec

### ISSUE THREAD

**Issue by amye** [cncf/toc#469]
Welcome to CNCF Project Onboarding!

Please ensure that you:
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/master/process/project_proposals.adoc#introduction
- [x] Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Has your project adopted open governance already? see http://opengovernance.dev

Formal onboarding:
- [x] Domain: transfer domain to CNCF/LF (ITx)
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners
- [x] Artwork: Ensure logos present on https://github.com/cncf/artwork
- [x] Website: ensure LF footer is there and website guidelines followed, analytics transferred
- [x] Create maintainer list + added to aggregated https://maintainers.cncf.io list - OWNERS file needed
- [x] Devstats: add to devstats https://devstats.cncf.io/
- [x] Marketing: update relevant intro + slide decks
- [x] Trail Map: update CNCF trail map if relevant (incubating projects and above)
- [x] Update https://landscape.cncf.io
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x] CNCF Welcome Email Sent to confirm maintainer list access
- [x] Schedule monthly project sync with CNCF staff

**Comment by amye** [comment]
Adding @paulhowardarm from the Parsec side.

**Comment by paulhowardarm** [comment]
Thank you @amye - I'm so delighted to see Parsec joining the sandbox. With regards to the checklist items above, will you be driving those and reaching out to me for help as needed? If I need to do anything proactively for any of these items, do please let me know!

**Comment by amye** [comment]
So the top checklist is for the project to confirm, the bottom is things we'll work on together: updating your website, etc. 
We'll need your logo files for our website, you've been added to https://www.cncf.io/sandbox-projects/ with a placeholder.

**Comment by paulhowardarm** [comment]
I think I can confirm everything in the upper checklist. A few comments below.

The final question "Has your project adopted open governance already?" - the wording of this doesn't quite match the heading for the checklist, which is "Please ensure that you". For Parsec, I think the answer to this question is "no", because the aim is for CNCF to be the way in which we achieve open governance. There hasn't been any pre-existing governance framework.

On the IP policy, I think we're already good - everything is Apache 2.0 licensed and we are using DCO sign-off for commits. There isn't a CLA, and we're not intending to have one for this project for fear that it could become a barrier to contributions.

The IP policy clause (f) states "all documentation shall be received and made available by CNCF under Creative Commons". Can I just double check the scope of "all documentation" here? Is this just documentation that is contained within the GitHub repositories that make up the project itself? It doesn't apply to external documentation about Parsec, such as blog posts or presentations? Arm and other partner organisations might wish to publicise the project through various channels. I assume that such publications would not be considered to be project documentation?

I believe that logo transfer is in hand.

**Comment by amye** [comment]
I've marked off the upper checklist, we're working on the logo transfer still so I will leave that open.

**Comment by amye** [comment]
@paulhowardarm: Checking in on adding the GH owners, I think that's the last big thing for you all as you don't have a website.

**Comment by amye** [comment]
@paulhowardarm: Any updates on adding the GH owners? Thanks!

**Comment by paulhowardarm** [comment]
@amye Sorry, I seem to have missed that this was an action on me. Is this another markdown file that is needed in the repo? How does it differ from MAINTAINERS or CONTRIBUTORS that are already there? Is there an example file you can reference from another project maybe? Thanks.

**Comment by amye** [comment]
Oh, so what we need is for  'thelinuxfoundation' and 'caniszczyk' added as initial org owners in your GitHub Repo. Sorry for the confusion!

**Comment by paulhowardarm** [comment]
@amye Thanks - I'm afraid you'll have to spell this out for me slightly more. Is this not a content file, but some admin-level setting in the repo, or in the parent org (parallaxsecond)? Is there a GH doc you can point me to so that I can be sure I'm doing the right thing in the right place?

**Comment by amye** [comment]
@paulhowardarm: https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/maintaining-ownership-continuity-for-your-organization should be more helpful.

**Comment by paulhowardarm** [comment]
Okay, owner invitations sent.

**Comment by amye** [comment]
Awesome! 
I will mark this issue as closed as the trademarks transfer may take more time.
