### ISSUE TITLE
Re-organize the TOC repo

### ISSUE THREAD

**Issue by michelleN** [cncf/toc#497]
We're still getting feedback that documents are hard to find in this repo. Please feel free to add suggestions or comment on what has been difficult in this thread.

**Comment by lizrice** [comment]
I really don't like that we now have a lot of duplicate info added [here](https://github.com/cncf/toc/blob/master/process/README.md) that was originally [here](https://github.com/cncf/toc/blob/master/process/project_proposals.adoc) 

I'd like us to reorganise the [readme](https://github.com/cncf/toc/blob/master/process/README.md) so that it's more of a table of contents, linking out to the more detailed documents
