### ISSUE TITLE
Question about a new open source project (not yet released) naming?

### ISSUE THREAD

**Issue by shillasaebi** [cncf/toc#502]
Hi CNCF TOC,

My name is Shilla and I am a CNCF Ambassador. We are creating an open source project (not yet released) that we want to eventually sandbox under the CNCF umbrella. We would like to use the name "Prombox" as in Prometheus Sandbox for the project name. The application will create an environment for editing and testing Prometheus configuration on the fly. Wondering if it would be ok to use that name and what the steps would be if needed to get approvals. Thank you! 

Shilla

**Comment by caniszczyk** [comment]
@shillasaebi that isn't a question for the TOC, more for CNCF staff due to the legal implications here, I don't think this will be an issue though: https://www.linuxfoundation.org/trademark-usage/


There is a "memberdesk" that Comcast should have access to as part of the CNCF End User Program where you can ask questions like this or even a note to info@cncf.io, especially if there are legal ramifications.
