### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Kubescape

### ISSUE THREAD

**Issue by amye** [cncf/toc#978]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [x] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [x] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [x] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [x] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [x] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [x] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [x] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [x] Is your project in its own separate neutral github organization?
- [x] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [x] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [x] Have added your project to <https://github.com/cncf/contribute>
- [x] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [x] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [x] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk
- [x] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [x] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [x] Website: Analytics transferred to projects@cncf.io
- [x] CII: Start on a CII best practices badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [x] Devstats: add to devstats <https://devstats.cncf.io/>
- [x] Marketing: update relevant intro + slide decks
- [x] Events: update CFP + Registration + CFP Area forms
- [x] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [x] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [x] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by craigbox** [comment]
* [x]  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
* [x]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
* [ ]  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
* [x]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
* [x]  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
* [ ]  Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
* [ ]  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
* [ ]  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
* [x]  Is your project in its own separate neutral github organization?
* [ ]  Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
* [ ]  Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
* [ ]  <s>Have added your project to https://github.com/cncf/contribute</s>
* [ ]  Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
* [ ]  Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

Things that CNCF will need from the project:

* [ ]  Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
* [ ]  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
* [ ]  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
* [ ]  GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
* [ ]  GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
* [ ]  Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
* [ ]  Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
* [ ]  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

**Comment by lukaszgryglicki** [comment]
DevStats page [added](https://kubescape.devstats.cncf.io).

**Comment by craigbox** [comment]
> DevStats page [added](https://kubescape.devstats.cncf.io).

Thanks @lukaszgryglicki!  [Please can you use this for the icon?](https://avatars.githubusercontent.com/u/100554170).

**Comment by lukaszgryglicki** [comment]
For icons we need official PR against `cncf/artwork`. It wasn't there when I was adding this isntance, once we have it in place, I'll update.

**Comment by craigbox** [comment]
> For icons we need official PR against `cncf/artwork`. It wasn't there when I was adding this isntance, once we have it in place, I'll update.

https://github.com/cncf/artwork/pull/381

**Comment by craigbox** [comment]
Domain is set up, so domain transfer ticket is filed.
https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25287

**Comment by craigbox** [comment]
Domain transfer is complete per ticket IT-25287.  FOSSA is set up, so the only thing we're outstanding on is a community pages space.

**Comment by craigbox** [comment]
Raised CNCFSD-1681 for community pages space

**Comment by craigbox** [comment]
Having spoken to @k8tgreenley we're not going to use Bevy at this point; we're going to use Zoom + YouTube for community meetings. 

I believe that completes the transition!

**Comment by amye** [comment]
Trademarks are still out there according to this list! 
We have a 'no registered trademarks' in https://github.com/cncf/foundation/tree/main/agreements

**Comment by craigbox** [comment]
I did not know that was a thing.  You learn something new every day!
Do you have a version of that template in an editable form?

**Comment by amye** [comment]
Sure do! I'll send you a Google Docs version for you specifically.

**Comment by craigbox** [comment]
@amye all sorted now with the assignment - anything else we need to see to?

**Comment by craigbox** [comment]
Both are long complete, @Cmierly?

**Comment by amye** [comment]
Confirmed, we are complete here!
